### ISSUE TITLE
[Task]: 

### ISSUE THREAD

**Issue by KevinMind** [mozilla/test-github-features#55]
### Tasks

```[tasklist]
  ### Tasks
  - [x] This is an acceptance criteria
  - [ ] Here is another one
  ```

### Description

Some description about stuff that is cool.

### Checks

- [X] If the issue is ready to work on, remove the "needs:info" label
